
inherit_from: .rubocop_todo.yml

require:
 - rubocop-performance
 - rubocop-capybara
 - rubocop-minitest
 - rubocop-rails


AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'public/**/*'

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/Documentation:
  Enabled: false

