name: Test Suite
env:
  BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, staging ]
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linter
        run: |
          bundle exec rubocop
          bundle exec haml-lint app/views/
  unit:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install imagemagick
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rake test -v
      - name: Upload Suite Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-unit
          path: |
            log/
  system:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run system tests
        run: bundle exec rake test:system -v
      - name: Upload Suite Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-system
          path: |
            log/
            tmp/capybara

