name: Test Suite
env:
  BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, staging ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libxml dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxslt1-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
  linter:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop
  haml-linter:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run linter
        run: bundle exec haml-lint app/views/
  unit:
    needs: [linter, haml-linter]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rake test
  system:
    needs: [linter, haml-linter]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run system tests
        run: bundle exec rake test:system
